### ISSUE TITLE
todo_11-8-2018

### ISSUE THREAD

**Issue by joemcglinchy** [NateMietk/HumanIgnProb#15]
set up amazon AMI
build out clip function
- see https://gis.stackexchange.com/questions/154315/splitting-raster-into-tiles-using-gdal/154400 

conda environment/commands for AMI
- scikit-image (+ spatial libraries)

**Comment by mbjoseph** [comment]
Hey @joemcglinchy - a couple of quick questions: 

- Did you have a particular AMI that you want to build upon? 
- Which spatial libraries do we want to install?

**Comment by joemcglinchy** [comment]
I have placed an environment YAML file in the python directory which i have found to be functional on my p3 instances. That was built upon the Amazon Deep Learning AMI. I think it would make sense to build off of that AMI, no? Specific to that environment is CUDA 9.

spatial libraries would include rasterio (dep. gdal), geopandas/fiona/shapely if we are working with geometries. scipy, scikit-image, and scikit-learn for non-spatial.

**Comment by mbjoseph** [comment]
Ok this is done: ami-06c3ceee7d06d0ca4
