### ISSUE TITLE
NLCD 1992

### ISSUE THREAD

**Issue by admahood** [NateMietk/HumanIgnProb#4]
the 1992 dataset comes with this note

NOTE: NLCD 1992 is not recommended for direct comparisons with any subsequent NLCD data products (i.e. NLCD 2001, NLCD 2006, NLCD 2011). The typical result of direct comparison will result in a change map showing differences between legends and mapping methods rather than real changes on the ground.

Still want to use it? or just stick with 2001,2006,2011?

**Comment by NateMietk** [comment]
let's add it to the suite of data and evaluate the aggregation from 30m -> 1km.  If it looks really off then we can toss it.
