### ISSUE TITLE
ICLUS Data starts in 2010

### ISSUE THREAD

**Issue by NateMietk** [NateMietk/HumanIgnProb#6]
The paper from Sohl (Divergent projections of future land use in the United States arising from different models and scenarios) states that the ICLUS data range from 1970 - 2100, while the Bierwagen paper (National housing and impervious surface scenarios for integrated climate impact assessments) evaluates the model from 2000-2100.  The data that is available on the EPA website is every 5 years from 2010-2100.  They cannot seem to make up their mind, and because of it we cannot use these data as housing and population proxies. Bummer.

@admahood I am thinking of moving back to the SILVIS lab's data.  The also have county level population densities and gridded housing density.

**Comment by admahood** [comment]
@NateMietk bummer... silvis housing density data is good but only goes to 2040 I think. still better than nothing though. perhaps, if we do the linear interpolation like max did, we can just extend it out to 2100? probably not legit though.
