### ISSUE TITLE
It works!

### ISSUE THREAD

**Issue by NateMietk** [NateMietk/HumanIgnProb#9]
@admahood I rewrote the function that creates transportation density in parallel.  It now works and we have (at this time) 4k hexagonal densities for railroads, transmission lines, and primary roads.  Secondary and tertiary are running now.  All we need to do now is clean this code with if statements. woo hoo!

https://github.com/NateMietk/modeling-human-ignition/blob/5de2848725b5b8568ea8873dbd29ddc6dd7aadf0/src/R/c_data_prep_transportation_density.R#L2-L56

**Comment by admahood** [comment]
@NateMietk woohoo!!

**Comment by NateMietk** [comment]
@admahood but now the population density script is acting up! - always something.  If you're in Tuesday let's sit down and chat.
